export const industry = [
  'Accounting',
  'Animation',
  'Apparel & Fashion',
  'Air conditioning & Refrigiration',
  'Architecture & Planning',
  'Business Supplies & Equipment',
  'Commercial Real Estate',
  'Entertainment',
  'Financial Services',
  'Food & Beverages',
  'Furniture',
  'Graphic Design',
  'Health, Wellness & Fitness',
  'Hospital & Health Care',
  'Information Technology & Services',
  'Logistics & Supply Chain',
  'Marketing & Advertising',
  'Mechanical or Industrial Engineering',
  'Motion Pictures & Film',
  'Nonprofit Organization Management',
  'Transport & Logistics',
  'Package/Freight Delivery',
  'Packaging & Containers',
  'Pharmaceuticals',
  'Printing & Stationary',
  'Restaurants',
  'Retail',
  'Sporting Goods',
  'Staffing & Recruiting',
  'Supermarkets',
  'Warehousing',
  'Wholesale',
  'Wine & Spirits'
];
